#!/bin/bash

##
# Crea la configurazione eks
##


source "${HOME}/var/workstation-setup/base.sh"

showHelp() {
   echo "Esecuzione container all'interno del pod"
   echo
   echo "Syntax: setup.sh [ -c;--company | -e;--env | -r;--role | -h;--help ]"
   echo "options:"
   echo "-h | --help      : Print help"
   echo "-e | --env       : Environment tentants"
   echo "-c | --company   : Nome company"
   echo "-r | --role      : Aws role [default: eks-console-staging]"
   echo
}

getargs() {
  options=$(getopt -l "help,company:,env:,role:,config-path:" -o "h e: c: r:" -a -- "$@")
  eval set -- "$options"

  while true
      do
      case $1 in
          -h|--help)
              showHelp 
              exit 0
              ;;
          -e|--env)
              arg_ENV="${2}"
              ;;
          -c|--company)
              arg_COMPANY="${2}"
              ;;
          -r|--role)
              arg_ROLE="${2}"
              ;;
          --config-path)
              arg_CONFIG_PATH="${2}"
              ;;
          --)
              shift
              break;;
      esac
      shift
  done
  shift "$(($OPTIND -1))"

  [[ "${arg_COMPANY:-}" != "" ]] || (echo 'Args: -c or --company [required]' && exit 1)
  [[ "${arg_ENV:-}" != "" ]] || (echo 'Args: -e or --env [required]' && exit 1)

  # Default role
  if [ -z "${arg_ROLE:-}" ] ; then
    arg_ROLE="eks-console-staging"
  fi

  # Default config path
  if [ -z "${arg_PROFILE:-}" ] ; then
    arg_CONFIG_PATH=${CONFIG_TENANT_SETTINGS_PATH:-}
  fi
}

getargs_osx() {
  arg_COMPANY=${1:-}
  arg_ENV=${2:-}
  arg_ROLE=${3:-"eks-console-staging"}
  arg_CONFIG_PATH=${4:-${CONFIG_TENANT_SETTINGS_PATH:-}}

  [[ "${arg_COMPANY:-}" != "" ]] || (echo 'Args: -c or --company [required]' && exit 1)
  [[ "${arg_ENV:-}" != "" ]] || (echo 'Args: -e or --env [required]' && exit 1)
}

main() {
  if [ "$(uname)" == "Darwin" ]; then
    getargs_osx "$@"
    aziona-environment $arg_COMPANY $arg_ENV $arg_CONFIG_PATH
    aziona-aws-assume-role $arg_COMPANY $arg_ENV $arg_ROLE
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    getargs "$@"
    aziona-environment --company $arg_COMPANY --env $arg_ENV --config-path $arg_CONFIG_PATH
    aziona-aws-assume-role --company $arg_COMPANY --env $arg_ENV --role $arg_ROLE
  else
      echo "OS not valid"
      exit 1
  fi
}

main "$@"