#!/usr/bin/env python3

import sys
import argparse
import os
import getpass
import subprocess
import json

EXPORT = ""

def argsinstance():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--active-path",
        required=False,
        default=None,
        type=str,
        help="Active path",
    )
    return parser

def main():
    args = argsinstance().parse_args()
    
    active_path = args.active_path or os.getenv("AZIONA_ACTIVE_PATH", None)

    with open(active_path, "w") as f:
        f.write("")
    

if __name__ == "__main__":
    sys.exit(main())
