#!/bin/bash

##
# Crea la configurazione eks
##


source "${HOME}/var/workstation-setup/base.sh"


showHelp() {
   echo "Esecuzione container all'interno del pod"
   echo
   echo "Syntax: setup.sh [ -c;--company | -e;--env | -p;--profile | -h;--help ]"
   echo "options:"
   echo "-h | --help      : Print help"
   echo "-e | --env       : Environment tentants"
   echo "-c | --company   : Nome company"
   echo "-p | --profile   : Aws credentials profile"
   echo
}

getargs() {
  options=$(getopt -l "help,company:,env:,profile:" -o "h e: c: p:" -a -- "$@")
  eval set -- "$options"

  while true
      do
      case $1 in
          -h|--help)
              showHelp 
              exit 0
              ;;
          -e|--env)
              arg_ENV="${2}"
              ;;
          -c|--company)
              arg_COMPANY="${2}"
              ;;
          -p|--profile)
              arg_PROFILE="${2}"
              ;;
          --)
              shift
              break;;
      esac
      shift
  done
  shift "$(($OPTIND -1))"

  [[ "${arg_COMPANY:-}" != "" ]] || (echo 'Args: -c or --company [required]' && exit 1)
  [[ "${arg_ENV:-}" != "" ]] || (echo 'Args: -e or --env [required]' && exit 1)

  # Default profile
  if [ -z "${arg_PROFILE:-}" ] ; then
    arg_PROFILE=""
  fi
}

getargs_osx() {
  arg_COMPANY=${1:-}
  arg_COMPANY=${2:-}
  arg_PROFILE=${3:-""}

  [[ "${arg_COMPANY:-}" != "" ]] || (echo 'Args: -c or --company [required]' && exit 1)
  [[ "${arg_ENV:-}" != "" ]] || (echo 'Args: -e or --env [required]' && exit 1)
}

main() {
  if [ "$(uname)" == "Darwin" ]; then
    getargs_osx "$@"
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    getargs "$@"
  else
      echo "OS not valid"
      exit 1
  fi
   
  if [ "${arg_PROFILE}" != "" ] ; then
    source <( aziona-environment --company $arg_COMPANY --env $arg_ENV )
    eksctl utils write-kubeconfig --profile "${arg_PROFILE}" --cluster "${EKS_CLUSTER_NAME}" --region "${EKS_AWS_REGION}" --kubeconfig "${KUBECONFIG}"
  else
    source <( aziona-start --company $arg_COMPANY --env $arg_ENV )
    eksctl utils write-kubeconfig --cluster "${EKS_CLUSTER_NAME}" --region "${EKS_AWS_REGION}" --kubeconfig "${KUBECONFIG}"
  fi
  
}

main "$@"