#!/bin/bash

##
# Crea la configurazione eks
##

# if [ "$(uname)" != "Darwin" ] && [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
source $HOME/var/workstation-setup/base.sh
# fi

getargs() {

  [[ "$ACCOUNT_ID" != "" ]] || (echo 'ACCOUNT_ID not valid' && exit 1)

}

writeconfig() {
  eval $(aws sts assume-role --role-arn arn:aws:iam::$ACCOUNT_ID:role/eks-console-staging --role-session-name eks-console-staging-cli | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\nexport AWS_SESSION_TOKEN=\(.SessionToken)\n"')
}

main() {
  getargs $@
  writeconfig
}

main $@