#!/bin/bash

##
# Crea la configurazione eks
##


source "${HOME}/var/workstation-setup/base.sh"


getargs() {
  if [ -z ${1:-} ] ; then
    read -p 'App name: ' arg_COMPANY
  else 
    arg_COMPANY=${1}
  fi
  [[ "$arg_COMPANY" != "" ]] || (echo 'arg_COMPANY not valid' && exit 1)


  if [ -z ${2:-} ] ; then
    read -p 'Env name (staging or production): ' arg_TENANT
  else 
    arg_TENANT=${2}
  fi
  [[ "$arg_TENANT" != "" ]] || (echo 'arg_TENANT not valid' && exit 1)


  arg_ROLE=${3:-"eks-console-staging"}
}


main() {
  getargs "$@"
  source <( setkubeconfig $arg_COMPANY $arg_TENANT )
  local res=$(aws --profile $ORGANIZATION_NAME sts assume-role --role-arn arn:aws:iam::$ACCOUNT_ID:role/"${arg_ROLE}" --role-session-name "${arg_ROLE}"-cli | jq -r '.Credentials')

  setkubeconfig $arg_COMPANY $arg_TENANT
  echo "export AWS_ACCESS_KEY_ID=$(echo $res | jq .AccessKeyId)"
  echo "export AWS_SESSION_TOKEN=$(echo $res | jq .SessionToken)"
  echo "export AWS_SECRET_ACCESS_KEY=$(echo $res | jq .SecretAccessKey)"
}

main "$@"