#!/bin/bash

##
# Setta le variabili d'ambiente in base all'applicativo e all'env scelto
# 
# INPUT:
#   - Nome applicativo
#   - Nome env
##

# if [ "$(uname)" != "Darwin" ] && [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
source $HOME/var/workstation-setup/base.sh
# fi

getargs() {

  if [ -z ${1:-} ] ; then
    read -p 'App name: ' COMPANY
  else 
    COMPANY=${1}
  fi
  [[ "$COMPANY" != "" ]] || (echo 'COMPANY not valid' && exit 1)

  TENANT=${2:-staging}
}

setconfig() {
  if [ "$(uname)" == "Darwin" ]; then
      if [ -z "${CONFIG_TENANT_SETTINGS_PATH:-}" ]; then 
        WORKSPACE_PREFIX=${PROJECTS_PREFIX:-"/Users/$(whoami)/Documents/projects"}/$COMPANY
        export $(grep -v '^#' $WORKSPACE_PREFIX/config/$COMPANY-tenant-settings/$TENANT/.env | xargs)
      else
        export $(grep -v '^#' $CONFIG_TENANT_SETTINGS_PATH/$TENANT/.env | xargs)
      fi
      export KUBECONFIG=/Users/$(whoami)/.kube/eksctl/clusters/$EKS_CLUSTER_NAME

      if [ -z "${AZIONA_PREFIX:-}" ]; then
        export AZIONA_PREFIX="/Users/$(whoami)/Documents/projects/azionaventures"
      fi

  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
      WORKSPACE_PREFIX=${PROJECTS_PREFIX:-"/opt/project"}/$COMPANY
      export $(grep -v '^#' $WORKSPACE_PREFIX/config/$COMPANY-tenant-settings/$TENANT/.env | xargs)
      export KUBECONFIG=/home/$(whoami)/.kube/eksctl/clusters/$EKS_CLUSTER_NAME

      if [ -z "${AZIONA_PREFIX:-}" ]; then
        export AZIONA_PREFIX="/opt/project/azionaventures"
      fi
  elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
      echo "Pls install Linux lol"
  elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
      echo "Pls install Linux lol"
  else
      echo "Unknown os"
      exit 1
  fi
  if [ -z "${CONFIG_TENANT_SETTINGS_PATH:-}" ]; then
    echo "$(grep -v '^#' $WORKSPACE_PREFIX/config/$COMPANY-tenant-settings/$TENANT/.env | xargs -L1 | sed -e 's/^/export /')"
  else
    echo "$(grep -v '^#' $CONFIG_TENANT_SETTINGS_PATH/$TENANT/.env | xargs -L1 | sed -e 's/^/export /')"
  fi
  echo "export KUBECONFIG=$KUBECONFIG"

  export DEVOPS_PATH=${AZIONA_PREFIX:-"/opt/project/azionaventures"}/aziona-cli
  echo "export DEVOPS_PATH=${AZIONA_PREFIX:-"/opt/project/azionaventures"}/aziona-cli"
  export INFRASTRUCTURE_PATH=${AZIONA_PREFIX:-"/opt/project/azionaventures"}/infrastructure
  echo "export INFRASTRUCTURE_PATH=${AZIONA_PREFIX:-"/opt/project/azionaventures"}/infrastructure"
  if [ "$(command -v aziona)" == "" ]; then
      echo "source ${DEVOPS_PATH}/venv/bin/activate"
  fi
  echo "export DEVOPS_TERRAFORM_TEMPLATE_PATH=$DEVOPS_PATH/terraform"

  eksctl utils write-kubeconfig --profile $ORGANIZATION_NAME --cluster $EKS_CLUSTER_NAME --region $EKS_AWS_REGION --kubeconfig $KUBECONFIG > /dev/null 2>&1
}

main() {
  getargs $@
  setconfig
}

main $@