#!/bin/bash

##
# Crea la configurazione eks
##


source "${HOME}/var/workstation-setup/base.sh"


getargs() {
  if [ -z ${1:-} ] ; then
    read -p 'App name: ' arg_COMPANY
  else 
    arg_COMPANY=${1}
  fi
  [[ "$arg_COMPANY" != "" ]] || (echo 'arg_COMPANY not valid' && exit 1)


  if [ -z ${2:-} ] ; then
    read -p 'Env name (staging or production): ' arg_TENANT
  else 
    arg_TENANT=${2}
  fi
  [[ "$arg_TENANT" != "" ]] || (echo 'arg_TENANT not valid' && exit 1)


  arg_PROFILE=${3:-}
}


main() {
  getargs "$@"
   
  if [ "${arg_PROFILE}" != "" ] ; then
    source <( setkubeconfig $arg_COMPANY $arg_TENANT )
    eksctl utils write-kubeconfig --profile "${ORGANIZATION_NAME}" --cluster "${EKS_CLUSTER_NAME}" --region "${EKS_AWS_REGION}" --kubeconfig "${KUBECONFIG}"
  else
    source <( lavora $arg_COMPANY $arg_TENANT )
    eksctl utils write-kubeconfig --cluster "${EKS_CLUSTER_NAME}" --region "${EKS_AWS_REGION}" --kubeconfig "${KUBECONFIG}"
  fi
  
}

main "$@"