#!/bin/bash

##
# Crea la configurazione eks
##

# if [ "$(uname)" != "Darwin" ] && [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
source $HOME/var/workstation-setup/base.sh
# fi

getargs() {

  [[ "$COMPANY" != "" ]] || (echo 'COMPANY not valid' && exit 1)
  [[ "$ENVIRONMENT" != "" ]] || (echo 'ENVIRONMENT not valid' && exit 1)

}

writeconfig() {
  eksctl utils write-kubeconfig --profile $ORGANIZATION_NAME --cluster $EKS_CLUSTER_NAME --region $EKS_AWS_REGION --kubeconfig $KUBECONFIG
}

main() {
  getargs $@
  writeconfig
}

main $@